### ISSUE TITLE
Support GHC 8.8

### ISSUE THREAD

**Issue by gwils** [haskell-works/hw-json-simd#52]
Currently we're waiting on https://github.com/visq/language-c/issues/65 before we can support ghc 8.8

**Comment by newhoggy** [comment]
Can I add you to the organisation? It would mean that you could push directly to the repositories and get CI and be able to merge.

**Comment by gwils** [comment]
Ok
Although I just made this issue as much for myself as anyone :)

**Comment by newhoggy** [comment]
You should have the invite.

**Comment by gwils** [comment]
Fixed now that there's a new `language-c`
