### ISSUE TITLE
Compilation fault on ARM arch

### ISSUE THREAD

**Issue by Bodigrim** [haskell-works/hw-json-simd#88]
https://github.com/haskell-works/hw-json-simd/blob/9a563edb3d1f391e212519bf85bad72e2995503f/cbits/intrinsics.h#L4-L5

This does not compile on ARM machines:

```
In file included from dist/build/HaskellWorks/Data/Json/Simd/Internal/Foreign.chs.h:2:
In file included from cbits/../cbits/simd.h:1:
In file included from cbits/intrinsics.h:4:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
```

It would be nice to add something like
```cabal
  if (arch(aarch64) || arch(arm))
    build-depends: base < 0
```
so that Cabal does not try to compile the package.

**Comment by newhoggy** [comment]
The change has been made.  Should I publish a new version?

**Comment by Bodigrim** [comment]
Yes, please. Thanks.

`hw-simd` has the same issue, if I recall correctly.

**Comment by newhoggy** [comment]
Done.  Thanks for the ticket!
